version: '3'
services:
  mongo:
    image: mongo:6
    restart: always
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=host2me
    ports:
      - "5000:5000"
    depends_on:
      - mongo
volumes:
  mongo_data:
